import React from 'react';
import { SVGDefaultProps } from './SVGDefaultProps';


const AnimationLoading = ({width,height,color}:SVGDefaultProps) =>{
    return <svg width={width} height={height} viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="50" cy="50" fill="none" stroke="#000000" strokeWidth="10" r="35" strokeDasharray="164.93361431346415 56.97787143782138">
      <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
    </circle>
    </svg>//<!-- [ldio] generated by https://loading.io/ -->
}
export default AnimationLoading;